import { createHash } from 'node:crypto'
import { lstat, mkdir, open, readFile } from 'node:fs/promises'
import { dirname, join, relative, resolve } from 'node:path'
import type { Catalog, StructuralSlotId, VisualSlotId } from '@qmonster/generator-core'
import { buildProductionEvidenceManifest } from '../packages/asset-catalog/src/evidence-root.js'
import { PRODUCTION_CHROMA_GATE_PROFILE, PRODUCTION_CHROMA_GATE_VERSION } from '../packages/asset-catalog/src/chroma-quality-gate.js'
import { prepareAnatomyBundle, type AnatomyBundleSource, type PreparedAnatomyBundle } from './prepare-v06-anatomy-bundles.js'

const VERSION = '0.6.0'
export const V06_FELINE_RIG_ID = 'feline-sit' as const
const STRUCTURAL_SLOTS: StructuralSlotId[] = ['bodyFrame', 'headShape', 'arms', 'legs', 'tail', 'extraAppendage']
const TRAIT_SLOTS: VisualSlotId[] = ['eyes', 'mouthShape', 'oralDetail', 'headAppendage', 'surfaceMaterial', 'pattern', 'colorScheme', 'effect']
export const ANATOMY_BUNDLE_SOURCES: AnatomyBundleSource[] = ['saffron-longtail', 'silver-curl', 'midnight-longtail', 'moss-curl', 'rose-longtail', 'umber-curl', 'ivory-longtail', 'violet-curl'].map(id => ({
  id: `feline-sit-${id}`, sourcePath: `asset-source/v0.6.0/anatomy-bundles/feline/feline-sit-${id}.png`,
  faceSafeZone: { x: 650, y: 280, width: 748, height: 620 }, featureSockets: { eyes: { x: 880, y: 560 }, mouth: { x: 1024, y: 735 }, headAppendage: { x: 1024, y: 345 } },
  mutationAnchors: { ear: { x: 540, y: 190, width: 340, height: 300 }, back: { x: 1320, y: 900, width: 310, height: 420 }, tailTip: { x: 1450, y: 1110, width: 380, height: 440 } }, allowedTraitPools: {},
}))
const digest = (value: Uint8Array): string => createHash('sha256').update(value).digest('hex')
const json = (value: unknown): Buffer => Buffer.from(`${JSON.stringify(value, null, 2)}\n`)
const portable = (root: string, file: string): string => relative(root, file).replaceAll('\\', '/')
async function writeNew(file: string, value: Buffer): Promise<void> { await mkdir(dirname(file), { recursive: true }); const h = await open(file, 'wx'); try { await h.writeFile(value); await h.sync() } finally { await h.close() } }
function empty(id: string, slotId: VisualSlotId): any { return { id, slotId, rarity: 'N', baseWeight: 1, themeIds: ['deep-sea', 'fungal', 'shadow'], themeWeights: { 'deep-sea': 1, fungal: 1, shadow: 1 }, compatibleRigs: [V06_FELINE_RIG_ID], assetPath: '', maskPaths: {}, origin: { x: 1024, y: 1024 }, socket: null, layer: slotId === 'bodyFrame' ? 'body' : 'faceAndHeadwear', semanticTraitId: null, semanticPriority: 0, excludes: [], boosts: {}, displayName: id.replaceAll('_', ' '), flavorText: '完整猫科解剖由对应 bundle 的连续源图提供。', description: `source-free feline anatomy bundle derivative ${id}`, archetypeIds: ['feline'], featureTier: 'base' } }
function idFor(bundle: PreparedAnatomyBundle, slot: VisualSlotId): string { return `${slot}_feline_bundle_${bundle.id.replaceAll('-', '_')}` }
function partsFor(bundle: PreparedAnatomyBundle): any[] {
  const parts = STRUCTURAL_SLOTS.map(slot => {
    const part = empty(idFor(bundle, slot), slot)
    if (slot === 'bodyFrame') Object.assign(part, { assetPath: bundle.structural.assetPath, assetSha256: bundle.structural.assetSha256, pngPath: bundle.structural.pngPath, pngSha256: bundle.structural.pngSha256, composition: { mode: 'bundle', bundleId: bundle.id, isNone: false, motifTags: [], visualIntensity: 'quiet', renderNodes: [{ id: `${part.id}-node`, assetPath: bundle.structural.assetPath, assetSha256: bundle.structural.assetSha256, pngPath: bundle.structural.pngPath, pngSha256: bundle.structural.pngSha256, parentSlot: null, socket: null, origin: { x: 1024, y: 1024 }, transform: { scale: 1, mirrorX: false }, layer: 'body', compatibleRigs: [V06_FELINE_RIG_ID], clipPolicy: 'none' }], geometryByRig: { [V06_FELINE_RIG_ID]: { sockets: bundle.featureSockets, faceSafeZone: bundle.faceSafeZone } } } })
    else part.composition = { mode: 'bundle', bundleId: bundle.id, isNone: true, motifTags: [], visualIntensity: 'quiet', renderNodes: [], geometryByRig: {} }
    return part
  })
  return parts.concat(TRAIT_SLOTS.map(slot => ({ ...empty(idFor(bundle, slot), slot), composition: { mode: 'attachment', isNone: true, motifTags: [], visualIntensity: 'quiet', renderNodes: [], geometryByRig: {} } })))
}
function buildCatalog(prepared: PreparedAnatomyBundle[], themes: any[]): Catalog {
  const anatomyBundles = prepared.map(bundle => ({ id: bundle.id, archetypeId: 'feline' as const, rigId: V06_FELINE_RIG_ID, poseId: 'feline-sit', structural: { assetPath: bundle.structural.assetPath, assetSha256: bundle.structural.assetSha256, pngPath: bundle.structural.pngPath, pngSha256: bundle.structural.pngSha256 }, alpha: { assetPath: bundle.alpha.assetPath, assetSha256: bundle.alpha.assetSha256, pngPath: bundle.alpha.pngPath, pngSha256: bundle.alpha.pngSha256 }, clip: { assetPath: bundle.clip.assetPath, assetSha256: bundle.clip.assetSha256, pngPath: bundle.clip.pngPath, pngSha256: bundle.clip.pngSha256 }, faceSafeZone: bundle.faceSafeZone, featureSockets: bundle.featureSockets, mutationAnchors: bundle.mutationAnchors, derivedSlots: Object.fromEntries(STRUCTURAL_SLOTS.map(slot => [slot, idFor(bundle, slot)])), allowedTraitPools: Object.fromEntries(TRAIT_SLOTS.map(slot => [slot, [idFor(bundle, slot)]])) }))
  const semanticSlots = ['frame', 'appendage', 'headAndEyes', 'mouth', 'surface', 'pattern', 'personality', 'quirk']
  return { version: VERSION, themes, rigs: [{ id: V06_FELINE_RIG_ID, sourceId: idFor(prepared[0]!, 'bodyFrame'), displayName: '正面居中坐姿猫', sockets: { head: { x: 1024, y: 650 }, tail: { x: 1540, y: 1320 }, eyes: { x: 880, y: 560 }, mouth: { x: 1024, y: 735 }, oralDetail: { x: 1024, y: 760 }, headAppendage: { x: 1024, y: 345 }, overlay: { x: 1024, y: 1024 }, effect: { x: 1024, y: 1024 } } }], parts: prepared.flatMap(partsFor), semanticTraits: semanticSlots.map(semanticSlotId => ({ id: `feline_${semanticSlotId}`, semanticSlotId, displayName: `猫${semanticSlotId}`, flavorText: `bundle 支持的猫${semanticSlotId}`, rarity: 'N', themeBoosts: {}, excludes: [], boosts: {}, visualMapping: {} })), modifiers: [], dependencies: { headShape: ['bodyFrame'], eyes: ['headShape'], mouthShape: ['headShape'], oralDetail: ['mouthShape'], headAppendage: ['headShape'], tail: ['bodyFrame'] }, compositionPolicy: { motifSlots: ['eyes', 'mouthShape'], surpriseRatio: 0.3, maxStrongFeatures: 2, maxStrongNonFacialFeatures: 1, optionalNoneRate: { min: 0.35, max: 0.5 }, frameBounds: { x: 0, y: 0, width: 2048, height: 2048 }, faceInsideRatio: 0.84, faceVisibleRatio: 0.84 }, archetypes: [{ id: 'feline', displayName: '坐姿猫', rigIds: [V06_FELINE_RIG_ID], defaultRigId: V06_FELINE_RIG_ID, requiredVisibleSlots: ['bodyFrame'], integratedSlots: ['arms', 'legs', 'extraAppendage', 'headShape', 'tail'], specialFeatureSlots: [] }], anatomyBundles } as Catalog
}
export async function assembleV06Catalog(options: { repositoryRoot?: string, stagedRoot: string }): Promise<Catalog> {
  const repositoryRoot = resolve(options.repositoryRoot ?? process.cwd()), stagedRoot = resolve(options.stagedRoot), assetRoot = join(stagedRoot, 'packages', 'asset-catalog', 'assets', `v${VERSION}`), catalogRoot = join(stagedRoot, 'packages', 'asset-catalog', 'catalog', `v${VERSION}`)
  for (const target of [assetRoot, catalogRoot]) try { await lstat(target); throw new Error(`V06_RELEASE_TARGET_EXISTS_NO_OVERWRITE:${target}`) } catch (error) { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error }
  const prepared = await Promise.all(ANATOMY_BUNDLE_SOURCES.map(source => prepareAnatomyBundle({ ...source, sourcePath: join(repositoryRoot, source.sourcePath) }, assetRoot)))
  const catalog = buildCatalog(prepared, JSON.parse(await readFile(join(repositoryRoot, 'packages', 'asset-catalog', 'catalog', 'v0.5.0', 'themes.json'), 'utf8')))
  const sourceHashes = new Map(await Promise.all(prepared.map(async bundle => [bundle.id, digest(await readFile(bundle.sourcePath))] as const)))
  const manifest = { schemaVersion: 'qmonster-v06-anatomy-bundles-v1', catalogVersion: VERSION, canvasSize: 2048, bundles: prepared.map(bundle => ({ id: bundle.id, sourcePath: portable(repositoryRoot, bundle.sourcePath), dimensions: { width: 2048, height: 2048 }, alphaBounds: bundle.alphaBounds, sourceSha256: sourceHashes.get(bundle.id), faceSafeZone: bundle.faceSafeZone, featureSockets: bundle.featureSockets, mutationAnchors: bundle.mutationAnchors, allowedTraitPools: Object.fromEntries(TRAIT_SLOTS.map(slot => [slot, [idFor(bundle, slot)]])), prompt: `Built-in image_gen complete feline-sit ${bundle.id}; transparent-background request; deterministic border-connected neutral-matte alpha recovery applied only because returned PNG was opaque RGB.` })) }
  const manifestBytes = json(manifest)
  const sources = prepared.map(bundle => { const part = catalog.parts.find(item => item.id === idFor(bundle, 'bodyFrame'))!; return { sourceId: part.id, kind: 'generated-transparent-layer', promptId: `v06-anatomy-${bundle.id}`, promptCatalogPath: 'asset-source/v0.6.0/anatomy-bundles/manifest.json', promptCatalogSha256: digest(manifestBytes), selectedCandidate: 1, sourceResources: [{ path: portable(repositoryRoot, bundle.sourcePath), sha256: sourceHashes.get(bundle.id) }], runtimePngPath: part.pngPath, runtimePngSha256: part.pngSha256, runtimeWebpPath: part.assetPath, runtimeWebpSha256: part.assetSha256, runtimeResources: [bundle.structural, bundle.alpha, bundle.clip].flatMap(resource => [{ path: resource.pngPath, sha256: resource.pngSha256 }, { path: resource.assetPath, sha256: resource.assetSha256 }]) } })
  const index = { catalogVersion: VERSION, extractionGate: { gateVersion: PRODUCTION_CHROMA_GATE_VERSION, profile: PRODUCTION_CHROMA_GATE_PROFILE }, sources, qualityGateSummary: { rigCandidatesEvaluated: 0, rigCandidatesPassed: 0, partCandidatesEvaluated: 0, partCandidatesPassed: 0, approvedRigSelectionsPassing: 0, approvedPartSelectionsPassing: 0 }, review: { generatedSourceCount: 8, invalidCandidateCount: 0 } }
  await Promise.all([writeNew(join(stagedRoot, 'asset-source', 'v0.6.0', 'anatomy-bundles', 'manifest.json'), manifestBytes), writeNew(join(stagedRoot, 'packages', 'asset-catalog', 'source-index-v0.6.0.json'), json(index)), writeNew(join(stagedRoot, 'packages', 'asset-catalog', 'audit', `v${VERSION}`, 'evidence-manifest.json'), json(buildProductionEvidenceManifest(index)))])
  for (const [name, value] of [['catalog.json', catalog], ['themes.json', catalog.themes], ['rigs.json', catalog.rigs], ['parts.json', catalog.parts], ['semantic-traits.json', catalog.semanticTraits], ['modifiers.json', catalog.modifiers]] as const) await writeNew(join(catalogRoot, name), json(value))
  return catalog
}
